---
name: Lint shell scripts

on:  # yamllint disable-line rule:truthy
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  pull_request:
    paths:
      - '**/*.sh'
  push:
    paths:
      - '**/*.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set reviewdog reporter type
        run: |
          if [ ${{ github.event_name }} != "pull_request" ]; then
            echo "REVIEWDOG_REPORTER=local" >> $GITHUB_ENV
          else
            echo "REVIEWDOG_REPORTER=github-pr-review" >> $GITHUB_ENV
          fi

      - name: Lint build shell scripts
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
          reporter: ${{ env.REVIEWDOG_REPORTER }}
          level: info
          filter_mode: nofilter
          fail_on_error: true
